#!/usr/bin/env python3
"""
Generate Static Laplace Frequency Table for QRES Range Coder.

This script produces the CUM_FREQ_TABLE used in ans_coder.rs.
The table is a Laplace distribution centered at 0, optimized for
prediction residuals from the transformer predictor.

Usage: python generate_laplace_table.py > table.rs
"""
import math

FREQ_TOTAL = 65536  # 16-bit precision (must match Rust FREQ_TOTAL)
SCALE = 10.0        # Laplace scale parameter: lower = sharper peak


def generate_table():
    # Generate raw Laplace weights for residuals -128..+127
    weights = []
    for i in range(256):
        residual = i - 128
        w = math.exp(-abs(residual) / SCALE)
        weights.append(w)

    # Normalize to FREQ_TOTAL, ensuring minimum freq of 1
    total = sum(weights)
    freqs = [max(1, int(w / total * FREQ_TOTAL)) for w in weights]

    # Fix rounding error by adjusting center (most probable symbol)
    diff = FREQ_TOTAL - sum(freqs)
    freqs[128] += diff

    # Generate Rust code
    print("// Generated by tools/dev/generate_laplace_table.py")
    print(f"// Parameters: FREQ_TOTAL={FREQ_TOTAL}, SCALE={SCALE}")
    print("// Format: (cumulative_frequency, symbol_frequency)")
    print("pub static CUM_FREQ_TABLE: [(u32, u32); 256] = [")

    cum = 0
    for i in range(256):
        freq = freqs[i]
        residual = i - 128
        print(f"    ({cum}, {freq}), // [{i}] residual {residual:+d}")
        cum += freq

    print("];")
    print(f"// Verification: cumulative sum = {cum} (expected {FREQ_TOTAL})")


if __name__ == "__main__":
    generate_table()
